services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: todolist
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5460:5432"
    networks:
      - my_network

  django-app:
    depends_on:
      db:
        condition: service_started
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DEBUG=False
      - SECRET_KEY=123123213
      - ALLOWED_HOSTS=localhost,django-app,127.0.0.1
      - DATABASE_HOST=db
      - DATABASE_NAME=todolist
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin1234
      - DATABASE_PORT=5432
      - CORS_ALLOWED_ORIGINS=http://react-app:5173,http://localhost:5173
      - DJANGO_SETTINGS_MODULE=to_do_list_config.settings
      - APP_ADMIN_USER=admin
      - APP_ADMIN_PASSWORD=admin1234
      - PATH=/env/bin:$PATH
    ports:
      - "8000:8000"
    networks:
      - my_network
  react-app:
    depends_on:
      db:
        condition: service_started
      django-app:
        condition: service_started
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_APP_PUBLIC_API_URL=http://localhost:8000/api
    networks:
      - my_network
volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge